openapi: 3.0.1
info:
  title: external-id-2-osm
  description: Service to retrieve mapping
  version: 0.0.1
servers:
  - url: http://localhost:1337
paths:
  '/entity':
    post:
      summary: Add a new external entity to the id mapping
      tags:
        - entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entity'
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '5XX':
          $ref: '#/components/responses/UnexpectedError'
  '/entity/bulk':
    post:
      summary: Add multiple entities in a bulk operation
      tags:
        - entity
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entities'
      responses:
        '201':
          description: Created
        '400':
          $ref: '#/components/responses/BadRequest'
        '422':
          $ref: '#/components/responses/UnprocessableEntity'
        '5XX':
          $ref: '#/components/responses/UnexpectedError'
  '/entity/{externalId}':
    get:
      summary: Get the entity by external id
      tags:
        - entity
      parameters:
        - $ref: '#/components/parameters/externalId'
      responses:
        '200':
          description: The entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Entity'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/UnexpectedError'
    delete:
      summary: Remove an entity
      tags:
        - entity
      parameters:
        - $ref: '#/components/parameters/externalId'
      responses:
        '204':
          description: Deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '5XX':
          $ref: '#/components/responses/UnexpectedError'
components:
  parameters:
    externalId:
      in: path
      name: externalId
      required: true
      schema:
        type: string
        minLength: 1
        maxLength: 68
      description: the external id
      example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnexpectedError:
      description: Unexpected Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
    Entity:
      type: object
      required:
        - externalId
        - osmId
      properties:
        externalId:
          type: string
          example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
          minLength: 1
          maxLength: 68
        osmId:
          type: integer
          format: int64
          minimum: 0
          example: 1337
          exclusiveMinimum: true
    Entities:
      type: array
      items:
        $ref: '#/components/schemas/Entity'
