global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development

image:
  repository: id-2-osm
  tag: 'latest'

replicaCount: 1

cloudProvider:
  dockerRegistryUrl: my-registry-url.io
  flavor: openshift

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  requestPayloadLimit: 1mb
  responseCompressionEnabled: true
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'

  metrics:
    enabled: false
    url: 'http://localhost:55681/v1/metrics'

# external
dbConfig:
  host: localhost
  username: postgres
  password: postgres
  database: postgres
  sslAuth:
    enabled: false
    secretName: secret-name
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt

initialDelaySeconds: 600

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  path: /
