name: tests

on: [pull_request]

jobs:
  tests:
    name: Run SERVICE_NAME Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out TS Project Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: npm ci
  
      - name: Run tests
        run: npm run test
      - name: Azure Pipelines Action
        uses: Azure/pipelines@v1
        with:
         azure-devops-project-url: https://dev.azure.com/Libot-Mipui-Org/exporter-trigger
         azure-pipeline-name: 'build-and-push-to-ACR'
         azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}  
